binop_separator = "Front"
comment_width = 95
condense_wildcard_suffixes = true
fn_args_layout = "Compressed"
format_strings = true
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
match_block_trailing_comma = true
max_width = 80
merge_imports = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
struct_field_align_threshold = 50
struct_lit_single_line = true
trailing_comma = "Vertical"
wrap_comments = true

